### ISSUE TITLE
Fix Fetch

### ISSUE THREAD

**Issue by DSchau** [pragmaticpat/g4-play-1#1]
@pragmaticpat  to fix

1. npm i node-fetch
2. npm remove isomorphic-fetch
3. Change `import fetch from 'isomorphic-fetch'` to `import fetch from 'node-fetch'`

**Comment by pragmaticpat** [comment]
Drag - thank you for giving it a look!

**Comment by pragmaticpat** [comment]
Interesting - node-fetch isn't compatible with Node 15 ( which is the min version for ARM / M1 ) - bumping to Node 16 since it's out and retrying...

**Comment by pragmaticpat** [comment]
😅 - upgraded to node 16... removed homebrew.. killed /node_modules... installed clean and ran.. now it works!
